language: node_js

node_js:
  - "8"

install:
  - npm install

services: mongodb

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on:
    repo: NamKiwook/To-Do-List-Back
  bucket: namtravis
  region: ap-northeast-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: namtravis
  key: backLatest.zip
  bundle_type: zip
  application: ToDo
  deployment_group: ToDoApplication
  region: ap-northeast-2
  on:
    repo: NamKiwook/To-Do-List-Back
script:
  - zip -r backLatest *
  - mkdir -p dpl_cd_upload
  - mv backLatest.zip dpl_cd_upload/backLatest.zip
