version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/To-Do/To-Do-List-Back
hooks:
  ApplicationStop:
    - location: script/stop.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: ubuntu
