version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ToDo/To-Do-List-Back
hooks:
  BeforeInstall:
    - location: script/npmInstall.sh
      timeout: 300
  ApplicationStart: script/npmStart.sh
    - location: script/npmStart.sh
      timeout: 300
