version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/To-Do/To-Do-List-Back
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
      - file
hooks:
  ApplicationStop:
    - location: script/stop.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: ubuntu
