version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ToDo/To-Do-List-Back
hooks:
  BeforeInstall:
    - location: ./home/ToDo/To-Do-List-Back/script/npmInstall.sh
      timeout: 300
    - location: ./home/ToDo/To-Do-List-Back/script/npmStart.sh
      timeout: 300
