version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ToDo/To-Do-List-Back
hooks:
  AfterInstall:
    - location: script/npmInstall.sh
      timeout: 300
  ApplicationStart:
    - location: script/npmStart.sh
      timeout: 300
